[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "Uit4YPvpH41rggra2Ljt5u7jNWSAGQns61vYQhfYFUY"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/crazycat/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
